inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - '*.gemspec'

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'redmine_activity.gemspec'
    - 'spec/**/*'

Style/GuardClause:
  Exclude:
    - '*.gemspec'

Style/PercentLiteralDelimiters:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false
