inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'redmine_activity.gemspec'
    - 'spec/**/*'

Style/PercentLiteralDelimiters:
  Enabled: false

Style/UnneededPercentQ:
  Enabled: false
